[color-theme]
name = "Forest Night"

[color-theme.base]
white = "#EEEEEE"
black = "#000000"
grey = "#333333"
blue = "#3EC3FF"
red = "#F04B3C"
yellow = "#FFF890"
orange = "#e0af27"
green = "#14665B"
purple = "#cba0ff"
cyan = "#27E0D7"
magenta = "#cba0ff"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$yellow"
comment = "#0e8f8b"
constant = "#E54286"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
"punctuation.delimiter" = "$white"
selfKeyword = "$purple"
string = "#2ebb74"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$yellow"
typeAlias = "$yellow"
variable = "#C1D9F2"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#21252B"
"activity.current" = "$black"
"completion.background" = "$black"
"completion.current" = "#14665B8a"
"completion_lens.foreground" = "#5C6370"
"editor.background" = "$black"
"editor.caret" = "$green"
"editor.current_line" = "#101010"
"editor.dim" = "#5C6370"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#090909"
"inlay_hint.background" = "#121212"
"inlay_hint.foreground" = "#999999"
"lapce.border" = "$grey"
"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "$grey"
"lapce.plugin.author" = "$blue"
"lapce.plugin.description" = "#AAAAAA"
"lapce.plugin.name" = "$white"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$green"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "$green"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "$green"
"lapce.tab.separator" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "$black"
"palette.current.background" = "#14665B8a"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "$black"
"panel.current.background" = "#14665B8a"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5C6370"
"panel.foreground" = "$white"
"panel.foreground.dim" = "$purple"
"panel.hovered.background" = "#14665b56"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
