name = "forest-night-theme"
display-name = "Forest Night"
description = "A true black theme with tasteful forest green accents."
icon = "icon.png"
version = "0.1.0"
author = "Nota"
repository = "https://github.com/ItzSwirlz/nord-lapce"
color-themes = ["forest-night.toml"]